### ISSUE TITLE
Bayou Transport gets disconnected when alt tabbed for about 20 seconds.

### ISSUE THREAD

**Issue by Debjoy** [FirstGearGames/FishNet#336]
Unity version: 2021.3.23f
Fish-Networking version: 3.5.8

**Describe the bug**
The client browser using webgl with bayou transport gets disconnect when alt tabbed after about 20 seconds of Idle. In Server it gives and error `Multipass connectionId could not be found for transportIndex 1, transportId of 0`. 

**Project created to reproduce the issue**
https://github.com/Debjoy/bayou-idle-disconnect-issue 

Built Webgl using compression mode "no compression" (Edit->Project settings->Player->Select webgl platform tab->Publishing Settings-> Compression format-> Dissabed)

Server running on editor using NetworkHUDPrefab buttons

Client running on browser using node command npx serve from command line

**To Reproduce the issue in above project**
1. Build the webgl game. 
2 Serve the webgl game folder using some local server tool. (i used npx serve)
3. Open the browser and go to whatever url the webgl folder was served (eg. http://localhost:3000)
4. In Unity editor run the game and click the Server button in top left to start server.
5. In browser click on the client button in top left to connect to server. 
6. Alt-tab out and wait approximately 20 seconds and you will see the error in the server, while the webgl client gets disconnected.

**Expected behavior**
Client shouldn't get disconnected from server when using a different tab or window other than the game tab of the webgl browser.

**Comment by FirstGearGames** [comment]
Just want to clarify I'll be investigating the multi-pass error. I suspect
the error to be harmless, but I'd like to get it resolved either way.
Bayou disconnecting is not something I can control. That's your browser
blocking functionality when the tab is not focused.

**Comment by Debjoy** [comment]
Sure, Thank you 🙇

**Comment by Alexei-Grigarovich** [comment]
I have a similar situation, same error: _Multipass connectionId could not be found for transportIndex 1, transportId of **680**_. After this error, you can not play on the server, the server disconnects the client. And with each attempt to join, the last number in the error grows. The error, as I understand it, appears on a random connection number, or after a long server operation (it worked for about a week). Dedicated linux server, webgl client.

**Comment by Debjoy** [comment]
> I have a similar situation, same error: _Multipass connectionId could not be found for transportIndex 1, transportId of **680**_. After this error, you can not play on the server, the server disconnects the client. And with each attempt to join, the last number in the error grows. The error, as I understand it, appears on a random connection number, or after a long server operation (it worked for about a week). Dedicated linux server, webgl client.

So the issue happens because the  Bayou TCP transport starts the clients with config that if there are not response for more than 20seonds. it will disconnect. Browser kind of stops the game or pauses the game when the tab is not being actively used. when that happens for about 20 seconds. The client disconnects. 
I have gone and change that value to about 120seconds. I haven't seen this issue ever since even after not using the tab for more than 2mins. Probably browser has some interval at which it just updates the tab which is lesser than 120 second mark.
You can also try going to project settings and in webgl build option set the "run in background" checkbox to true. That might also help in keeping the game active when not actively being interacted.

**Comment by FirstGearGames** [comment]
Either of you able to verify if this is still a problem on 3.7.1+?

**Comment by Davey111** [comment]
> So the issue happens because the Bayou TCP transport starts the clients with config that if there are not response for more than 20seonds. it will disconnect. Browser kind of stops the game or pauses the game when the tab is not being actively used. when that happens for about 20 seconds. The client disconnects. I have gone and change that value to about 120seconds. I haven't seen this issue ever since even after not using the tab for more than 2mins. Probably browser has some interval at which it just updates the tab which is lesser than 120 second mark. You can also try going to project settings and in webgl build option set the "run in background" checkbox to true. That might also help in keeping the game active when not actively being interacted.

Do you remember which part you change that fixed it for you?

I edited line 58 of Bayou\Core\ClientSocket.cs from 20000 -> 120000

`TcpConfig tcpConfig = new TcpConfig(false, 5000, 120000);`

However, this issue still persists for me.

**Comment by DevDavey** [comment]
After debugging further it seems it is the server ending the connection after not getting packets from the client for 20 seconds.

Changing Bayou\Core\ServerSocket.cs line 88 to `TcpConfig tcpConfig = new TcpConfig(false, 5000, 120000);` improves the duration that you can be alt tabbed longer but does not solve the issue completely.

Even though I have the TimeManager's Ping Interval set to 1, when alt-tabbed in the browser, the outgoing heartbeat pings from the client get slower and slower until they surpass 120 seconds.

Going to investigate further.

**Comment by FirstGearGames** [comment]
This isn't a bug, most browsers block data when alt tabbed.

**Comment by DevDavey** [comment]
I found a fix! Editing the .jslib file at: `FishNet/Plugins/Bayou/SimpleWebTransport/Client/Webgl/plugin/SimpleWeb.jslib`

`// this will create a global object
const SimpleWeb = {
    webSockets: [],
    next: 1,
	pingIntervals: {},
    GetWebSocket: function (index) {
        return SimpleWeb.webSockets[index]
    },
    AddNextSocket: function (webSocket) {
        var index = SimpleWeb.next;
        SimpleWeb.next++;
        SimpleWeb.webSockets[index] = webSocket;
        return index;
    },
    RemoveSocket: function (index) {
        SimpleWeb.webSockets[index] = undefined;
		SimpleWeb.stopPinging(index);
    },
    setupPinging: function(index) {
        const sendPing = function() {
            var webSocket = SimpleWeb.GetWebSocket(index);
            if (webSocket && webSocket.readyState === WebSocket.OPEN) {
                // Create a binary ping message
                var buffer = new ArrayBuffer(5); // 1 byte for PacketId + 4 bytes for timestamp
                var view = new DataView(buffer);
                view.setUint8(0, 14); // 14 is the PacketId for PingPong
                view.setUint32(1, Math.floor(Date.now() / 1000), true);
                webSocket.send(buffer);
            } else {
                SimpleWeb.stopPinging(index);
            }
        };

        document.addEventListener("visibilitychange", function() {
            if (document.hidden) {
                if (!SimpleWeb.pingIntervals[index]) {
                    SimpleWeb.pingIntervals[index] = setInterval(sendPing, 10000); // Every 10 seconds when hidden
                }
            } else {
                SimpleWeb.stopPinging(index);
            }
        });

        // Start pinging immediately if the tab is already hidden
        if (document.hidden) {
            SimpleWeb.pingIntervals[index] = setInterval(sendPing, 10000);
        }
    },
    stopPinging: function(index) {
        if (SimpleWeb.pingIntervals[index]) {
            clearInterval(SimpleWeb.pingIntervals[index]);
            delete SimpleWeb.pingIntervals[index];
        }
    }
};

function IsConnected(index) {
    var webSocket = SimpleWeb.GetWebSocket(index);
    if (webSocket) {
        return webSocket.readyState === webSocket.OPEN;
    }
    else {
        return false;
    }
}


function Connect(addressPtr, openCallbackPtr, closeCallBackPtr, messageCallbackPtr, errorCallbackPtr) {
    // fix for unity 2021 because unity bug in .jslib
    if (typeof Runtime === "undefined") {
        // if unity doesn't create Runtime, then make it here
        // dont ask why this works, just be happy that it does
        Runtime = {
            dynCall: dynCall
        }
    }

    const address = UTF8ToString(addressPtr);
    console.log("Connecting to " + address);
    // Create webSocket connection.
    webSocket = new WebSocket(address);
    webSocket.binaryType = 'arraybuffer';
    const index = SimpleWeb.AddNextSocket(webSocket);
	
	SimpleWeb.setupPinging(index);

    // Connection opened
    webSocket.addEventListener('open', function (event) {
        console.log("Connected to " + address);
        Runtime.dynCall('vi', openCallbackPtr, [index]);
    });
    webSocket.addEventListener('close', function (event) {
        console.log("Disconnected from " + address);
	SimpleWeb.stopPinging(index);
        Runtime.dynCall('vi', closeCallBackPtr, [index]);
    });

    // Listen for messages
    webSocket.addEventListener('message', function (event) {
        if (event.data instanceof ArrayBuffer) {
            // TODO dont alloc each time
            var array = new Uint8Array(event.data);
            var arrayLength = array.length;

            var bufferPtr = _malloc(arrayLength);
            var dataBuffer = new Uint8Array(HEAPU8.buffer, bufferPtr, arrayLength);
            dataBuffer.set(array);

            Runtime.dynCall('viii', messageCallbackPtr, [index, bufferPtr, arrayLength]);
            _free(bufferPtr);
        }
        else {
            console.error("message type not supported")
        }
    });

    webSocket.addEventListener('error', function (event) {
        console.error('Socket Error', event);

        Runtime.dynCall('vi', errorCallbackPtr, [index]);
    });

    return index;
}

function Disconnect(index) {
    var webSocket = SimpleWeb.GetWebSocket(index);
    if (webSocket) {
        webSocket.close(1000, "Disconnect Called by Mirror");
    }

    SimpleWeb.RemoveSocket(index);
}

function Send(index, arrayPtr, offset, length) {
    var webSocket = SimpleWeb.GetWebSocket(index);
    if (webSocket) {
        const start = arrayPtr + offset;
        const end = start + length;
        const data = HEAPU8.buffer.slice(start, end);
        webSocket.send(data);
        return true;
    }
    return false;
}


const SimpleWebLib = {
    $SimpleWeb: SimpleWeb,
    IsConnected,
    Connect,
    Disconnect,
    Send
};
autoAddDeps(SimpleWebLib, '$SimpleWeb');
mergeInto(LibraryManager.library, SimpleWebLib);`

**What I've done is added two functions into the javascript:**
setupPinging - sends a ping packet to the server every 10 seconds when the browser has changed tabs
stopPinging - stops pinging when the websocket has closed

setupPinging is called inside the Connect function. 

This seems to keep my websocket connection alive basically indefinitely.

It seems that the browser is throttling unity to the point that the pings stop being sent. However this workaround will keep the websocket connection alive. Even though the ping packet isn't quite what the server is expecting (timestamp instead of tick) the server throws no warnings or errors and does not close the connection.

**Comment by UnityEQ** [comment]
@DevDavey thanks! This worked absolute perfectly for me, I hope @FirstGearGames includes this fix!

**Comment by FirstGearGames** [comment]
I replied via email and did not see the patch until after visiting the issue on git.

I'll modify the lib file and bundle a new release! Thanks!

**Comment by zlengos** [comment]
i fixed this increasing values in tcp config in ServerSocket, ClientSocket and increased value _remoteServerTimeoutDuration in ClientManager (it was not in the scene, so i cant see this value)

**Comment by DevDavey** [comment]
Few bugs fixed with this patch. (and a bug introduced in the SimpleWeb update) 

Also by using a web worker the setInterval throttling is fixed.

https://github.com/FirstGearGames/Bayou/pull/21

**Comment by SnaiperoG3D** [comment]
Sorry for necro but are we talking about this file?
https://github.com/James-Frowen/SimpleWebTransport/blob/master/source/Runtime/Client/Webgl/plugin/SimpleWeb.jslib
In new version there is no ping, and i still facing issue with window collapse on 4.6.22 Fish, 4.15 Bayou and 2.3.3 SWT
